# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04d200130f2805d512ef3d8fbfde86b0f215b6ab4a8ae731cf33253f00ea6b9328b9012be1679fbf351e10929404fe419bdacf98af4ae8a4e4c842c592d6c018

test:
  secret_key_base: ba58a1203d1e4e1cac999c7d443c884f527d24b8f750998d08fbca525bee5cc31f596492e9397efd53f5b322226f98dc3ce11f3898d043a0a004970d1891abf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
